services:
  # MYSQL Database
  mysql:
    image: mysql:8.0
    volumes: 
      - wordpress_db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3307:3306'
    networks: 
      - wordpress_network

  # WORDPRESS
  app:
    depends_on:
      - mysql 
    image: wordpress:latest
    ports: 
      - '8000:80'
    restart: always
    volumes: 
      - './events:/var/www/html/wp-content/plugins/events'
    environment: 
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks: 
      - wordpress_network
        
networks:
  wordpress_network:
volumes:
  wordpress_db_data: