services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
volumes:
  mysql_db_data: